name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  vitest_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-versions: 20

      - name: Cache Dependency
        uses: actions/cache@v4
        id: cache_dependency
        env:
          cache-name: cache-dependency
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}

      - name: Dependency installing
        if: ${{ steps.cache_dependency.outputs.cache-hit != 'true' }}
        run: npm ci --progress=false --silent --no-audit

      - name: Run vitest
        run: |
          npm run test:coverage

      - name: Show coverage
        uses: davelosert/vitest-coverage-report-action@v2
